apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-apps
spec:
  storageClassName: nfs-omv
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${CONFIG_NFS_SERVER_ADDRESS}"
    path: "/apps"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-apps
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-omv
  resources:
    requests:
      storage: 1Mi
