apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-archivio-personale
spec:
  storageClassName: nfs-omv
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${CONFIG_NFS_SERVER_ADDRESS}"
    path: ${CONFIG_NFS_KUBEDATA_PATH}/syncthing/Archivio Ricordi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-archivio-personale
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-omv
  resources:
    requests:
      storage: 1Mi
