---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: k10
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: kasten
        namespace: flux-system
      interval: 5m
  values:
    #externalGateway:
    #  create: true
    global:
      persistence:
        size: 5Gi
    grafana:
      enabled: false
    prometheus:
      server:
        enabled: false
    injectKanisterSidecar:
      enabled: true
      namespaceSelector:
        matchLabels:
          k10/injectKanisterSidecar: "true"
