---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: k10
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: kasten
        namespace: flux-system
      interval: 5m
  values:
