# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:K8deqp++93eHJDEwg0XWcmoyRHco5ODboA==,iv:h3ixKaWrxmGn5mxvH6kvxH1r76mf8gYhJR7VPMFNzf0=,tag:Hjik0fmO3FJqU/n6PUaTEQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5tx0J10spiucf+VpsBRfxlJxxy71odgV9HClzpsdu08GwV+3ZQ==,iv:jMMYjAsYa3nt/Lc3KtZptyhyTmR1y5EUlLSZewD5afo=,tag:3vIHMr3RECShEhAGUnOCaA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:X2XNdE1elsdjABFoRaBgzf9a,iv:5++Fhoh1NEtVAv7bY8mhaQGC3eUjBsNIOehL2p323Uo=,tag:t8OgecGhFM2+mZF6Ed1idA==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:dL4TN7cb59aLmtgv/Q==,iv:UR/Y8pgEpINXHE9hquE42UpHm1XSJwWlmoiqhCpdaGk=,tag:0onLhbpFQkiGujMyuoLRlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd0hwK1lKUENWM3YxTzd4
            WTA1ZTBjeGVKNHgvWlpQT0VzZE1qM0hHdXlRCjZCMm5MM0pQR2gzNHBqQ0NKM2tp
            NnZoaFhNTUE2aE8vUmQ5bkc3QVZ4VXcKLS0tIDNjL0JIVXRRRW9ySHluZGVLZ09y
            b3ZpcWNOdGRqZDJKWHVKcE1qdkRxeGMKzBGEPPySykhL6BpWmd5RclEROYtYxFwK
            yHtTWPSu+xCi4MbgbP5MfESiKqDdhUp5KoWmTQ4cTbUuaRqPjL+j0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T11:10:59Z"
    mac: ENC[AES256_GCM,data:lFX2hFaJ0kBBllBuJQWAwBBjb8NZx84Ahoo156VbpOq54QIMAt/ne9bCIoqaktysErgiUxjmhI5cOtpIf6PavZ2L9MeEx3mvqXBivg+mjF1gad2F0CPeyGuzhYOcl6nOPhfJwUwoEkygeOYOhHEJAJil2KsVJGQWmKe8zPfAgAg=,iv:lFyN2P3H1mLfIQdtGSujSd482w1XuZ19FdedRqacdaQ=,tag:ZSXTkSmhbBhq6Vg6VYu+2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
