# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nAeUmZp0djzvDOrlmYgm6I25Oblh/8qvEg==,iv:OaxeEyzjrjyjJS8E8NXMyAOpTi2CQ55nuP230vSHltU=,tag:U/Fol5iAqxXM3YkiZZYltA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:4kTB/VyI7gwhB2YqysDijjTLSDaBPIbanuXagj8Mi4Mc3IthPg==,iv:HwV4RbZN/Pob/jsdJkRnkdDQN8CjozREbdPurNI6Fmw=,tag:do4hsLF1M7N6RUaK4G6ilA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vnVu/6KLnEO4ITvutBltxcrU,iv:6AehlhT9V7xOyjYdsoDoS19qge2IR/yTpLB+/x7FJmg=,tag:t5kf2aVNDNDMSrc3FRJT/g==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:f9AoX4V+OfxSxaaaPA==,iv:PQ3lQadAo6Jwfp64A3IQJYeAHjqI+fOejZcb1mQ+Nsc=,tag:cuLJ9b8j9rdjI1RlnOA3+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMmRVaFFxT2Y4ajNOZnpR
            ZHJZNzhHODFMbmdnUEIzTlRZZzI3VXFuRVhrCkFQZG9ydTJLZzIweUdscGFYdjJ5
            QjJmdkVCdk1VUDlmT01yVVZIOE1EUEkKLS0tIG0vRHozclRSbS9pOGVWZ1RBajY3
            Z0IrUEkvNEthNVJrVklHcjdkazA5RmMK6DcQCW4XknET9kqZ9QZX6CIqRxt/WJNX
            rRx/qcaXLSMVRZ6ZY1vCJLCCc09ivE99K3Z2fUwnuoXSzrE/HEZgHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T11:05:51Z"
    mac: ENC[AES256_GCM,data:YkidexfyDOik7WKrAGMUSEy1t+FqIk7SYPJekeEElozSd2kC7ZJ8eH8mHBfoWbptYpfFzBSU+Pdnt3Lx8Uj/ZAAkvSbwq+/ow17YdxG8HEQpgWfVGYqZxp6Ki96AS/a9MElVijLTvcNb55pHhTkOc0W0vu1GWYLfSbuZAxCOie8=,iv:5Q9qUs/MQZayGnU9z/ClunhfE6RyP8iC6Z86255i+9g=,tag:9Y8P6IBmANSkJ7he+37B1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
