# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kbQLpvtGps8j56QTEIo0kO8ltYiIs3voOg==,iv:edVR7541JxoTsN9YASj94tFD7NenbIYK8i9evccpmjc=,tag:v1cxoFD7PrEppgDk2fSZuw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:DbyFOcx70hn/4DcBw7ceAhIKS7mbV8jo/7wR0t2nqxzb6F0znw==,iv:y3idn9f+/bSB+mpZ4nN2g/pcipEKd/B59ARxx+22Rm8=,tag:xlpLJPHNxnRQpeAJ1BeLbA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:L7So8KYSdYp+yjTSokM5R4Uu,iv:o1UpP5oefWhwYmvlkPJi2RS4R0HYrqh/PlmBorlb/Vg=,tag:CGNvQckm7WfmW42K3lvxJA==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:FC3tTyisApxklMTqew==,iv:OOSs1ssnp3KzST50hMnk/cFIA3eWJOQtuojfPt2XJgE=,tag:nszqYONkhFC2Ib1zVOLuOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSHI3eHVTd3JlWENlWDdj
            WjUxcE1XVW5kdlM4QW91R29hb21kVThOcG1zCjhhVk0wSWUxR0R4eGZrUVR4Z2wx
            RlBGOERPNkFiTE5jRFN3UUlGcEUrdmsKLS0tIDR2UCtjUDZDR2graEt2V09ZWVp0
            dksrOTQ0U2NuNVBmbGNjZ3ZvMThJVzQKHTRI4/pMzppGUImSk4i7BpLiF9HEpnrT
            JN3ehCqpOXG3kq3iKyNfO2M6ZfOpg5hINExGnQxdZmYIg7aE67sQ6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T17:41:25Z"
    mac: ENC[AES256_GCM,data:DjagpL9Tjs6iYX/olf+nJJ4Y6wERaKLgtayB23J8CkWCMCTC0upWMupX5QbNht0i5bOhGQXZ1DnX/U9sv+gpnaJHuLWoCeLIGtkdmVXpqsxoXM9khxIAMBIqos78DPV+lFqK0WIIHx7MJ4vW3d3L7V2lKM2CSTYSNH+QLUXs+BA=,iv:x8mnQzk8j+OqTtmyI1d4PqbHdY/h44L1FjczYeWeQuw=,tag:jxorV3JusF3dYh9fOdvYaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
