# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UnMI7qi/WiIsi71SN40qCBrWP0xNRURnvQ==,iv:7BNpY0RcrwCv/yIKoyYLQiTw2X5J6HqjlfE3DkEUVss=,tag:xqPE/29CmCE5uSfmrD643A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:tDRdLGLmlSWVynFE81AGi13DeLVmqVBPk2j7JhYT3nbqelrs+A==,iv:skFnPu/8OZWOk+RhkRh85/TV7CE5EdFrQnRjGhq7uOc=,tag:nu53q7xjuuD6cElCDZkTYA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:pPVZjmu0tKR99GEFK4JtSzY3,iv:tmocsj57JDTNlKtsPj9rzUMUZ/76ozdX40BOQiVWbTo=,tag:gFwWBUikUAo1E4lax3fctw==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:tQEOYRrpMhEpuiOqMQ==,iv:6OErovftpuEEMXlw/8G7GU/gZPm9TSN+G0KZOHYbjjI=,tag:VGJdyCyyeWzKsUqlTsIuHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVzNUM01jR05lTGxLQ0ZP
            aUpxREZVZFJDdzA3VW1NWmRqQWVuNzBPRlhVCnNqUllQRlNtNTFiR3lFY2xrYW1X
            QlMwSlkvZkRGaWJHYnNrVnI4NmNXdDAKLS0tIFFtZU1ZM3RVbHZKQVNNLzFpaFdS
            OXJEQXlvNE1hNHd2bkE3QzZKVFFMVnMKqFSZll5eTUkK6Ow4MGQ2EERRib3EY8PT
            MH1bOgr482zqhOxSw3kefGct2zxRDNYyaFY2nNJm0TNbIeyw9+CKIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T14:09:44Z"
    mac: ENC[AES256_GCM,data:2hVAtT6NvOPbt7rskquDvnaRXWLFaNo0BzFG98niqkQ0utlrnL8UxvldvMHcb7t0Ux2fqr/0F6QJxIv/XN9Qt4UmJ/OMmkv0FgAPF3HJRXOU08c5CNTrhMdWT6yPmto1w4zTQNgUECSrmBZwDmfe4s08ZiMvoXWacOLZCFtprfQ=,iv:2I9QrltxuyyT24T31OLSquUphII0EbVfNIt8qagRiIA=,tag:W9DyeQZ/4/9PLInFyDlPMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
