# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:g3HbdzDRMSmpkl7PcV/SGKdq3V2Ouk99bA==,iv:nktfXUSbCDPYHhAdsoJ1YPLrPZifuHDoXdZU8TK/c70=,tag:/JezJTu/a0Ggtd+KDqEM9Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:JVRm7ARL9WPNiJihtNQ5oIed6qrc8P2deQ0YFk3B9B+UaqcmUg==,iv:WC04eqx4mzqolCHz10KpJ1wXhGDUoCx4/6uBgWWBeKI=,tag:q2TENatFdBW+EruU9Thp6A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:5j6+BylhJ8ltjaGiXMtW7nR9,iv:yaN9EBj+/Ev749VEBGiUXUgi469d0E9I/PsIZaWqHQE=,tag:1S5NRjCRN3mCunSDQdk6LQ==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:t9w+oy9nG6KAhmsOxQ==,iv:bYQcDaGEMDJd1AUgfcQup0ArVkBIZ65/pLPuDA6xbr4=,tag:DJg/mA+qTnIiSxzbyvZaLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUXVJb2Q3dExtcEExelZP
            TWtZd2YwN0ZKSGdMM2sydG1jaEN1U2lGOGtvClhVb1pqQ2xmUCthVUtJcVRJUDkx
            YXlsanRkcXk2WmJsajRDNEhDWngxZWsKLS0tIDREV1k3UWpwaW5vQ3lhdC9oQ1Rm
            N0g3aStXd3A4aEFhdHhXeTh0RHhvSm8KIZ+IA9p0u8vuqxR6AFmD9g4y5FOKVdGr
            OLhsC3rF+UHvdkJsTqrEbYLFH1d7TMX1QVMvqY9Br6Rt6L/IyClGlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T10:31:52Z"
    mac: ENC[AES256_GCM,data:nWAv+9VQQoWLM6GW5+66/M4vHaSSCNCYELRjUvKekASvUC0u6zLdGWCblmVpqFW1VW+zaSUSliVBlFZbjwrEVUN1kZFlHGAwWrE8WsmlDS9bfwLdlk1mvV/ynvuivv9CYjNQfTW3siTzBMef8M0osL6goQPtI4p9VbwWoWcgME4=,iv:rARpWBLdrqbvU4tfBdGbiwii1T6rzMr13kBjF7Aa7z0=,tag:+BmWXNyEB0YcXpNhIgDVyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
