# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Wx+T7TKvQae0kV0BNrk2ympFqKO+Dm/Qkg==,iv:H4EwhhETrTq9kDZGdl5aYW9tKkwo2V0VUuSMuKUwHVY=,tag:WD91TgyAIK7M/NT5V1KQzA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5O2rMA0KRKlV9AVU1ANydU9TBWWncZ9nGMsL8foXdgrgq36DGQ==,iv:v1e3JVBxL1hWLZHC2Z2ySgf5UZxkJCbPV4m3dqsTFgU=,tag:lphSbF7Q+FTZUhet3YvXqA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:wnuYBd912X4R9iIjOsJ1nBCj,iv:6Y1ts7RqdshHsy9qy1jq+QbWEp9eLhA3Y58WcJecO4A=,tag:ysDl5qSO1kDdohp2c4Z4ow==,type:str]
    CLOUDFLARE_DOMAIN: ENC[AES256_GCM,data:zT4Wg3+p9BrOvjkz5g==,iv:qL9D3jlpG2xkgr7LcNcvCI0TDX3ShxY6pdjveRosdzk=,tag:conV1VHWBtmbMdENxVqOLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVTRHQ0M0Um5VTFBaWkwz
            eG5lek1XekJUYkZ6MVZlR0FyZk42c1UrSHpFCkFGTDFzN09SUEUweFBza1BQckoy
            Y3AvSWdMRE1EYmx0K0ozNmVvdDFsZTQKLS0tIEZ0N01IRTllNC8zU1FjWlpQY2xx
            NTlRMEtTdTNodnJwL2ZWdmVqbnZrV0UKoMyKnoQCG9h1AJl9GShB2RoO7WLzECIQ
            Uze/a+UBG5xnLqDE6vrI0tnFi++5lR+oaogwkT0jm6vmoiW1kFaI0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T11:24:25Z"
    mac: ENC[AES256_GCM,data:NXlgULRNZ6k2iiHNJeA91Tp6alxonvDiAlLvyD0peixax819Cs5AqBX3UEETO61NJiGAcioSyMJ7SPYls4+EQwGAJm9AAX1OLYsBFHPe6gfoUrR/Rvm3VElmS1CXnu6CF6C3uvEV5jNdkEKKn/rYgCa7l03mQNkZUQr0BVxjYwo=,iv:bKhPyr63gLT9PQj9nsKsVlIa1iufUX2f+pKdbehVyW0=,tag:xT9Dw22zABObgb52GBcGwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
