# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:GUWPEx4vi7kBX8R5yqPCzfrsyow+VGdLeYC6l/2x275EXY4EYA==,iv:EcSJOL73pYP+epNJoR2hjhMJMoFTfRWQP/7dB7+H9WA=,tag:fFXn5KK7atZ2Me6A0oOtBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTUo1Z2JJamZNU1RlNmUx
            OStKK2Q0NE8ydlh0ZnN3WjBjYWZBbmdzdFd3CjlDNWhXNk5WSDNmb0E0SzVDZkxx
            L3BEMEpManZZZTlCR1BoVDVBd3ZsOFkKLS0tIEJaS21NdW83NkgwbTFqUmhaMGht
            VEJtcGJHYUZGUGVCS2srYVYxR2VuUWMKAklpzBlraYlOBH5PNGckv/jUly3xPYoy
            pjy553DwDuKglADM7wD8eCPt8LvzWH+GYIgGAO3RyebwWpTdo3UmuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-01T10:29:00Z"
    mac: ENC[AES256_GCM,data:zG1v13mYv1dSZWY+z04Uz+hB7AOPDVCnQCDVJ7iNVseHaYl1mmwd3/NctM+w9YdaDocPQdzJAyput89Y4U6f0O9vPBOn3/G3nEUKYUGrjZMOhI/XYfQs3PEfWBU6t7seKVW+kdHqZHUWcLiFNnc/BiLpQ8vaphdbusmzbkFMg4Q=,iv:p2vBs/Xt4rIlKpY1nEaj4AN1LglpQpuBEyKw5U8fSEs=,tag:CS3Lv4TyCpI1RCZc4P1MEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
