# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:UdBpm1M+pfhK9QU2P8JAgIEORb4CEbS0aN5BBOFugT4F7vxEoQ==,iv:FpJlFngKR1aFWGJrk+oaD7NySUFSBlpSUOI81HH8HqI=,tag:bx9/6o6RIS85pkSQaVKVMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMzArRjl3a3plRVlKTUND
            ZTAyditmU1NoUjlCbmRPOE9vSUwrenVQVlc4ClBlY3N6UGtOdGdFT21tZFVaMGF4
            QlV0NE16NnA4OVAzak9rbTBKdGxSRTAKLS0tIFQzSWxpeTVQRXUySUhMUHZDYksw
            SlI4bWxUQ2hPaG13STE1bUdJZUt1MEkKRYqhrW4TnqJH0WhfsqTZqAucmqec2B7N
            AryiEqSDDBOiQ2Z4bHYURm6M1ISiojIVNSSzTckiAx1i9EuNiTJLHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T16:35:01Z"
    mac: ENC[AES256_GCM,data:CWhxvFERvHVqH8k9P+IVZUJ4nyTGBdJwSI8F047tAuTToPr550MBp5f7EMtsLrbfwgf89onq90V1UhAWQH5po9h9USQ4g/slKcu9wqX7/3QbxBkXjXTpqaeDP0uJybxQLov2UvIyamLHWYYxN/tCPC6Hh24jhwQo8/IZW3e9cGA=,iv:gEse6q6vRxWwYVeTMPa4nUrSypqZG6vHKxxdHKqdDq0=,tag:1g+80yO+9VnNH4TUM0svKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
