# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:w7I0GmczCDJr2+PA8XZ/ETQkmWlHmccvEQ==,iv:eXzaV1oPOKpd01dPcY6fNd8dgrbUTxNe11qbvCHTfg8=,tag:v/fbOypLR+EdZULqdYWs1Q==,type:str]
    api-key: ENC[AES256_GCM,data:UiS0L+kzk6JPEIjq/5Ecfe/Qv8oUcp8cl6/VNUhq2OSK8HtGiw==,iv:bxCeLYjYelXSYBnY5D5fIAB2mvrDwcnEDVQ+a6CMZSc=,tag:aE73RbsMLdJqpO9UAz9pQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSER0T2hTS3NnVThZSWpu
            R2JhaytXMDVsaVlaSis4bWlIaXdsNEdoc2hZCnV0YlYxdXJTL1JCQkN5RWo5MHV5
            Y2FYWU1rempyNndoU1NKTmJnZU1objAKLS0tIDJSNklQZUt0SXM2R0pKQUx1T2Ev
            QlA5aTk0TzFDZUU0ekpYeGtGTTlRaEUKs04NYE+wXX4xk9AvdcaneMuFsatNvSxu
            KCUtBOGKECtuERcneupkbUbEtkjmHmV/XCkwf68wEPeAHA/5VYKG4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T10:31:52Z"
    mac: ENC[AES256_GCM,data:YIXEn4BId+fPhtnV79L2WkzG257uVsAEN+2AE1Gwh5IWlaoZONPRByB7hgw/aQ7VS8btOMBRzJMVJEuAgqbXBLDjM96j1yzBPO3gnRWt/+8zhsLGoII1xmSrYSUZfNOCoKJq9PzuTNMbzfsqIoEeaaA2SQCDINp8gCJFeWMbIIQ=,iv:coh/3lUheP8o+KYczQ6wrP9PLsso1dfR7vodCY1PnDc=,tag:gczv6BM+gf7LCBwfpe3e0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
