---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 11.3.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
    auth:
      rootPassword: ${SECRET_MARIADB_ROOT_PASSWORD}
    persistence:
      primary:
        enabled: true
    podAnnotations:
      backup.velero.io/backup-volumes: data,config
