---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mariadb
      version: 11.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
    persistence:
      primary:
        enabled: true
    podAnnotations:
      backup.velero.io/backup-volumes: data,config
