# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:x/pRpyz45IhymYtWK/QSBoGM/mVNhk7Bg6qh/4UGkZFiLA1QUHXK2f80n9y1Unbpz2AsM/Dt44uwFikU,iv:XMOW9jEdC4kOM1fh6QF8xtiawwo1DFVKL6FgKWyZ3/4=,tag:pqt5XXYUh+yDQfifzxJSTA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CepGARyAgZoqvKo/nw==,iv:Zk/A0Sx07Yr4Asap3xSnCGsi9fuYWVSl3fzUxOqQTA0=,tag:xlIy1zQYlYRVFoHIhOUN5w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CqZ5Ldx2qkfRNvR4hdO3yFVloMu0JIyUdA==,iv:f8GPm2S78618xeZvC4eAcL5Bcrdpz8pzcoUckMGLHvY=,tag:TsBQ4gXw/cwUnlwmLCHfOg==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:l5+GtLlMgA8=,iv:fGfCt/z1wG7J4qLJoKYuHco+tyN8BZwnwca+nuuKzeI=,tag:HQ3/L1TjsFMKZyiXYbu4gg==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:P2c13dY=,iv:CFQNn12WMRmDD5IelS917f15wkV8Hd8ErvZa9LtJtQU=,tag:z8VgbyQbkXjt9cmevvukzQ==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:5PfmkX1fIDJRxnvkD41pu6m+SGqoXkl0jag=,iv:eKOcbtC+0Y91Biy61CSDeRdqE/a6tc0oT4wpkcPJ/FE=,tag:O62E4Etvv8cWhG7kbN8zhQ==,type:str]
    SECRET_K10_AUTH: ENC[AES256_GCM,data:ALYE9+Og0EWvFnD2pZthGcmlQXwgle1VNYUdTuS4FIj23wBUCLX/bqk2kg==,iv:+jESNj40wOQGg5AuGA43aiTheajf8E2qQ5ZsYA17q/g=,tag:kdyQohgXJok7nOhNQZjIZQ==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:ZAZds83PyUODuzVViNt8WiZLvhjnxE5e9lh7A37eoB5rCeSV8hXqtgCbC/NraDAkAOE9h5BAkWFhWYwq1pFpGjzkD0OsSBUM,iv:slYGRBuN5aQeUvNRkL3UIR4iBjB4rS0VhC5ido+CUBA=,tag:lWqXLtgzT71V8j/j3/7Ijw==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:F+xvA7IL1nxREsmBVGibbGvajBNLd97hNuEEzJltssrFnPs=,iv:HW+p46i//S53quGOecLAGIijQyrTi7CtA9QI+CM/X9I=,tag:KpCdy/ntL5YOh5k3kA+YUQ==,type:str]
    SECRET_GOOGLEOAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:z8fLXq4RzNpNdU1WwGIZATbfE7fnzOCrEc9dY/5AZTo=,iv:rsZWegS+A0irABpFOmUAQGNCnekDqinpLA2TF2Bw6UM=,tag:LRqVmZxZHrdsfF//XslGww==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:7ooEBIa2ELspAoYU3gvm3E5102mRIj4f6MK46nk9ZRo=,iv:bTCObYQdsAvkVT/hApHLkFxkh3AxzMK8f1rfoLlZ5eI=,tag:+POb3So9p36FkFi1jnfSgA==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:PKUif4VzgWRQXxH9gVG7qNpLf0DfEHr1uu1lveTQIcc=,iv:tlrrJKyQHf1ny4wx5dgAftn1Uj4BGkrvc02BZaFZAE8=,tag:PTE3QVAQNw/mvIsuMXrwBA==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:kHJrGr3Vn9RmjR95CIXPq9gTue5eXmctdqKN+BPiykV/Fz3EkwHicA==,iv:b17uaBKBXTcf2I/csTlUC6k1S/N616wEiQPFxnm5CY0=,tag:xFevjlxTvvAbQcdYRuPDZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZWZsQUNHMSs3TUlSRU1I
            SGpIL1BmWS9teFhjYWFhQXBWdS9CZUZRbG1FCmRuMTJ3bzBnajdJUmVzYWFUUkZt
            SU15WkJlQ0g2cFViaVE2by9mOVVPeWsKLS0tIDRTY1J3aHFKMk05S01mK0dYY3ZL
            bFc0bkhBYktQdThCVi9TOSs4SlNwK1EKWoGPNiqT1LjOYGlRTOBPF7V+pEX+QCQJ
            JxsFX4yYn/4O+Y3UNTJziai6LsUh9oB6JiCYwnAFPJo1+0Hj+vM8Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T11:08:33Z"
    mac: ENC[AES256_GCM,data:iU36zt2jD+1dB4eLMRQ55Mpu2R2hvHXAb7HIDBEtWvgPA9AWxeAvPxQmkCt9rMnaNOxv0P8gZoMiGmn+jJLTXYPs462zkl/uEJhVV4R+3nr4DrO9asnB/0vGZBINs+HARDCahS4aa5C8uGQZbsyZu3kzoDqcG5AAepCstjFhOQI=,iv:whl41GLGsuWFwd8uajyWneVM0Z2YNNWQ+PO7NK1iD1s=,tag:bvC1ODCkCqME5nQbgaCpHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
