---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Rome
  METALLB_LB_RANGE: 172.24.1.9-172.24.1.20
  METALLB_K8S_GATEWAY_ADDR: 172.24.1.9
  METALLB_INGRESS_ADDR: 172.24.1.10
