# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:dpB0L+p2G6WD0wysapOzHUTZ+b3C+eDl5NOFs7T0D1HrvJr3mwjOKmP+hrm2KBORme7bjBSOPB6FLoNk,iv:cxTKl40v5Cag7xLEdiIxd9LLp2Y7CjpqYD25akfKUNY=,tag:OeHV7/5hCIEQe+tkp/I+Yw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YqUx+E5Ef1uAoEKQQw==,iv:SOTjeNW0Ayxd0WN0LisBMD2fYr2TNjsxUrcSqm0DmYY=,tag:tp8wO22kkERThVJhOuQppA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C+84j9nM9lzFxnUlo3BOjlVVYZ/Y5Qa9Zw==,iv:fM0jUk+5jFoMCLQtkYyW+vl/KI85u6ZUYmp0hl9Lc8w=,tag:b39DId98xYIkrZfep8OJ6A==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:HOcJoeH4Xxg=,iv:PGvzzBASJYSL9WRyvUdKuI+Z9Ths4kb6caAAuqimwZg=,tag:jHYSaGCFF7M6Ei3yBOvoPQ==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:AJ/oepM=,iv:bAOzHtWGy42X7T1+ABtVWKzAdW1V1eXhsxt2+ae0rcE=,tag:Cp727tU1rzKn8WtI2CEk1Q==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:kqCVim6biUr7ayajU0eP9UpND2UAuAbBvbc=,iv:NtsInUgVXqhY9lIc47YeBXZ5VbChneIJdvpzoUMq4Fo=,tag:BmmRJODhC+ltUa7a61D3lA==,type:str]
    SECRET_K10_AUTH: ENC[AES256_GCM,data:ywbnbEplCFYdOcK4sozNXUKvR0Lmjte/6k+KWVeHW4M+UcXMuCPHVb4JdA==,iv:YEQUCrtB+WhhraEFZ4wBR4ZZuEd85519nl68D7Bmjug=,tag:4aIvvmzTEqEwc2D8pO0ddg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:CiSAQGA+Dk7PQDCSt5S43ppWniWmesnCN/9TjbyBSifJMng9OsXYSnOSN4++ZxhBYjclfuU93Cn/JxtpL5s8Wo1AuPmg4NvG,iv:EHl6s0TdRDzEHiXpwp/cRJ3FdqM2xebgENp0ffEpJls=,tag:RqL4VmPzGnm1enpU5YV+MQ==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:0v+o2uVZ4TMBL2EBASUk6QEolS0QnCFPTxy+ZhvODBxaW88=,iv:71PHsvEZVBYHgQti+bOrcoA8N4F9bJ2rL/HWMNWLjA0=,tag:3oHs3VUFurY+AwNphl+yuA==,type:str]
    SECRET_GOOGLEOAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:7bpKdsfiU3TYeiijQY/FFe6F34uAdYP3bLfdPh1t85A=,iv:NG6+l85w5M1/oL+/4JgIY/B0F7ftQ8EfVBmkUYab+vA=,tag:gauwtAv3APzKvHIKcHI+/Q==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:zUyuhqLL38ubuCaM1ePxAGmnQ8ND6XWxG3TZjj7L4+I=,iv:8XJ0PoOWYkqzFVwLVk9lULwoKZ1Gr+YuhROLO4RnbBQ=,tag:/W5ZZWLmDWRo5YsJsDP1Jw==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:VuUClO8FGwxGrgrEp27GfoAE80NsNx7Jb83/rfc8nVU=,iv:fi3yZ3r1colm9tc6Kup1AwLyIAI6LhCguOKNj23bpzM=,tag:LqYaQdSs0aXFW9mJmwJRQg==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:3/9OF0aTzZj/FVdvp4GZGZma0co0R5xP64i+t+7nzSaGYJlwXjRuvg==,iv:upN3mt5Ccz6qr8WusMRAYJOB9jn9CoLmYmMgmmTDoRE=,tag:cFJqB64M94JnWNzLhZw4gg==,type:str]
    SECRET_WIREGUARD_CONFIG: ENC[AES256_GCM,data:fJHvhPi3SlbIQydRDAx7jJkjWAlEj8wgK3zTdMUa2ZuwwDJcqecVfvB9Z+12y3J0F0v0PDX79EoJ1Jq9aDCvzuA6ztqjW127Tq2Yrgd21cICH1Nlqk8NG3k59sKaha1G8zQVR13ThM9wA7YjpjQHe2pouSaRwfPQj/v0xgYmnGI9qdbTEEZlN/jZk0VniZUMvff8YQXSp59DfQns09T/CwhCOuFN9AsaMYIoYMF/SVrS00zDMXipByXQwFttcqhwUkGFOSnw3L8r3yYak4EwdXmE0ZnoAHDECj3OpJHvGoY+wJk8HDLUknN2G1zof0cH2RvCtS6MA7trabthQtPAw8dCUtM2qAM0/Hv1Ct8y6IC1GcY4Zl1CHC1Lig6qHHXI876ZAtWpa3E37qb3hb/+5i9H56wzwTjy2N/6tp6YHh18d9R/SNq0bLpHxXGcYP+6W3b8vfNAcvhx8nBETi/UsF4l/aEXuAZuH8GV5WRGUWWnL/rNKDHYgD/tN74CLbFbsJFW7gGc6haG48T+NyKtCcZPstrmiKBbv2GvrGubkRqvwG7wDMCxa/O0DLoewVtvnrwDU3G80UgU7zXlBq6+vzZqJ/MpWZxAlcs1Vy5Q2v0wPegTC4yOQh0UYxRtbGnAyTdVBHKMT/r06ZNqmCr0QiL+5dH4HXrMwHKA0Ralq4++7lRJK97E8aMqexvI/3ljlCp1NrKRuRjXSNwGyQTdNI+vrI+h5KYuGq99rlH6eo90ljU9mbXwQuCzoMuby+VuZLXVkXRD6jKnqAvzMJ+zCvT3oheOo2NzkFoaKWRN31E7dRhl+H0cKdYg3gpMkilPYre1VOs2N3qdgJouU8xtwhlddJehaHH7cM74AoVRnrCuybRAD0t/6Cf2qXnCiU6nHsoK7gXXJ8hqd5vZorUfecGkkUZgOYXgK4TEzCrHf3zmTbdakhhNAl9ke4rkkCnrUlUgv3TA/OQF06AnERvxS2tPR8pBmiZnPk+T7w10PW41oQUVjl2h+UBsoHTdEnRDy1UVtJgBe9M=,iv:sL0Vl5lYXZIAUChiCJ2NL7sVY0uBBukfJLT0mDybOJA=,tag:m34Q0Xb8Nozfql1G40SCvg==,type:str]
    SECRET_WG_ACCESS_SERVER_PRIV_KEY: ENC[AES256_GCM,data:c0Ve3usE8P4vF4HhU3Rg3tAVDvW/7aNgRRGV7ThAd5PlY2vNTnXe+ik0qvU=,iv:fd5a1EypC3WCovqy5rdqw3YthqfrgD73aUbk+kNBi6U=,tag:BwdHVzdMUfmWXivSe7f6oQ==,type:str]
    SECRET_WG_ACCESS_SERVER_ADMIN_USER: ENC[AES256_GCM,data:1Jb1b44=,iv:a/Myg5VFhYKZFRPpLZIS1PcFsHZuSjO4EgJOVVFe3YU=,tag:4WKRuYui8X0S/dwV0HPnqw==,type:str]
    SECRET_WG_ACCESS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:pmxPKUYi,iv:zqLI2dqz9hlpFcHuDoZo72SzaGRx1PNw4fN2xmcdSDs=,tag:k6p27v0dX7G51BM+3BTLQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYit2T3NQVVFpVzVmUlNV
            Z2pJQlgxWVVCV2Y3YVhWckp5aEFYZUZKS1VJCm02YUprQS9vQ2MrazFWZEtNU0dL
            WVVXZEJGTXhQbFArMGhoNzdIWFh6OXMKLS0tIHB3Q1hKZ20wNFYwRTZDNjNrV1ov
            WHlSTGxpLzlUamk0OFA4eU9DVUU5Qk0K9bSBXkSPfCYw8amWwV+PtIqea/uh4KEc
            0ThbEUGSoqy2a6qAIZDdGRfnulfbIagCy5omo2flG49/4xUHg4996w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T16:35:01Z"
    mac: ENC[AES256_GCM,data:dxX/xdznnmPFwtpoYO+NV/OrtiwoUuauD0+dlqpD0Q6pyyFPN7YJZM37Znh/5pJU45wEqOfTeK9QzWtqdqh6HA+8XgpuH3FEaERKMRUoolZ8yWcI1vG4k7dgauaNbomH6XHkezOEXkPvL6VVVeJn4CkInDTbBQFcHeuVTpFxfhg=,iv:4RR1CDkuaGiDhV2hPTP5vzHcC7UKClx/aXdp4XPxDwQ=,tag:Ixxg8CJv44QD0WxT6EnRig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
