# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_OPENHAB_BASICAUTH: ENC[AES256_GCM,data:b+CWOqOMP/LXA0wQ0XQViHJ2hN1Qe8bi/9+DcFe7Xj+49DpQy6eQHSP8liGLBRjfq8kDD5q8qGrmdVY3,iv:aGyeVB0tYaB8fO6YDy4ZrKeKxLx0bU1taTMk8s7m2wk=,tag:2D0DPUNz58U76QJwu5y+Tw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bC/1MlpPygmd7ZC8uQ==,iv:xNpaujpmyQ7gnMrgpsnVrMt9TaBN9/1UjljDOOtlriI=,tag:2gP4p39Ckw4n2flKUZW+iQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:85rXLQNJz5kUFIWwGyaiLaTrBILk3i1Skg==,iv:cR7CoNOdlzQiE66rlL7YX637gNBhRrnWCJgf3Ijj+sM=,tag:lN+Je0tztdxYEzIdNgP0Aw==,type:str]
    SECRET_MINIO_ADMIN_KEY: ENC[AES256_GCM,data:fDMGD+XzVTM=,iv:T3+Snz5fs+Pbk5nAjJBN1WKxkiW8eqvc4m/YJCxZFJI=,tag:HvfkqpoEQs1KVnQ2P8AUVw==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:yLXBGws=,iv:xQV4T787pux3MzYcqID8QDMmQVdztnReH7USeBYmLFE=,tag:QAtg17tvSsZyx7c5Jfzyrg==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:G7HUaTGMfvS651FyJKgGprip/0dkgLgA0no=,iv:sBUBeeOFbSkplbq8fJVNiFr3FNktlNsMOnvz5fjZEIo=,tag:JzNfx8r2xcIKrKXu6Qmljw==,type:str]
    SECRET_K10_AUTH: ENC[AES256_GCM,data:rd8DEuzcRcy95T864eDNjNkbGb15GLbqojVJLFpd4AYxgGb8HdGhZXQGJw==,iv:bnfCszGOwtZu7+LUAuZ7QxW4gHiq1myIA+3QoSk5rLo=,tag:BySpjKrc113BSX8bi3wSJg==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_ID: ENC[AES256_GCM,data:NTJUsb9gHfgbRWmmo+SX3U/0We62w90qG/8a6vmE+WBCftjw1jz8YhMrAB42P4+fJZnDiV10A0rBMLSo25rA9xmWK/AdgHGq,iv:v1tgl2yHdzypLN5VNWoW7u9Ih1g5qpiXEI3aJAWX5jE=,tag:xJ7f5e6IIK7OtqX7b+zC2Q==,type:str]
    SECRET_GOOGLEOAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:0N5IqGZqFyqeSgP6zRz5zrBzPU24A8B9bQKRbgDFoo5mGzU=,iv:3uJ7+xYg1etaD8lXIUgtzwMyI2sojBEwO8v2Y3zQFcs=,tag:J5nEvQLcFRFpxLSL44DfoA==,type:str]
    SECRET_GOOGLEOAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:8mT5588/sqNnvw8N92uZlyExSxeLBDQ+8euQhH+Dw7k=,iv:/01tgP16Bg+OFfpTqV1VnPwFcawy/FomPZ65tRxI7Yg=,tag:CEwt5q2IQalo1M0ag8yqzg==,type:str]
    SECRET_DDNS_CF_ZONE_ID: ENC[AES256_GCM,data:tcnZIOhLXIaYB6K4+O+F06BHN4xZ2upJ6JnbWRUCsG8=,iv:1adFpPMwSEi8O1dQ1P0DsZUCo2Wg9jHf88sj4q+ksc8=,tag:OvK161VjNI+5nv5krBT7Iw==,type:str]
    SECRET_DDNS_CF_RECORD_ID: ENC[AES256_GCM,data:ax9zo+6GhMf34P++O+EI/4AfCwA7GhQctAsOWULcrBo=,iv:qiATqv2OfOWmJJyCHZX9p9Wuo/tAXmR8YGqfvbXhQZE=,tag:O/DkoHRFQmndynq+m8WNcw==,type:str]
    SECRET_DDNS_CF_AUTH_KEY: ENC[AES256_GCM,data:kknfm58dd4Lj9o8nVu94BwT6kOyYXBwec5cyhwND1PUcEa/JaUDZ2w==,iv:VKXL2X14qHnEZPYdP4q+1LTUbQ48F7DNx3exrouU4mI=,tag:Bxm0apK3kiEKctpntunwwA==,type:str]
    SECRET_WIREGUARD_CONFIG: ENC[AES256_GCM,data:egIfoT5E5VI2C39+mb72+wBxPTcn8q8pIvvyvxLv6bHSrm+ctG8pe6nxfp6fkIqBDnY6c8Qq3E0neF2J/MzhKfCCXJDsS6htEjIDK4w8w7OiPADWOsvbtz6UybBYgcjSOh31ocRBSNmXttiuMiNhQiR3byVdr/8Z9ZlaweYHavs4jg4Ldl/tNWYIen5HD44yMSaqPXIlJyh9fV8zgWwzbbvCrPIDJs6aXUeVtGtTlqd97WYfc/rbBltOT+4eNUvhT7x+uYmXNa0FclFpJRFIHZHUcLGK0iZXcRdSCI9kPV3+s2rnKUYnfPWQ/vEzSaiGYpDqozr2mO7xQO2JlUjVNdE7ZF4tud+iqccSJInNMqbJhv9dawLcx6ChYlWlTm3ImMnh7J8vkCtrBmmic2LPuJidwIHDJgfZ1PY0MwIWakb4JUvI2QI7GHExdMsB+jtHtb5KdTyf3+UuB0YnCnYKZNT1r8YPhnI0+a/QZ1qNkVE7Q2EHg9vHMrWJUSTm3ivFdUYxSmCehaoAyxG5rgdEv1toYLBzfHz5XCoAEd02iSzSY7Who4O2Qr+BDm9fnB09ZL0hHeFFuI6Ml11vj6JU4NiEKHysBo93mhDcSwWqhSOU2+h6mLGaoJLgxEAJj7nXAaeCXjgPneFbl0tLi/9kGbTRlPC9odtqgCdXz34xcAV5PYfnBaYGbsKF1747hgWQpj5QhQF2cjdydXzEkiD4nN+CWSiQFIcvp5x86zkXJU6PhbX12J46xxj91mwy9gPIAapvQ0/yg1IWdy5Q6oiQT6t0rfKFd3D8v5cXVYBKXXf8vxgmYwl0vJS+31hUcW2Axuqyq3HKOCTcf2YHdsfNC/duK/aNyhkHC3o/7yXz627fp9zRpgfRcDHB53qE/rZChJu889Wo6uI+RgZDwcPU3cOpwzNgGwXabXiIipadeJecQD5IZZTjPMLtTq6YM6Ba+4d3cNGyDbzWjALm8Wkwr7wa4TecbMaM8vGsRnRZ5LjHjxPDvUepFRRKc1ZZsGZtiO7su8dh5pU=,iv:hAQeit74oBCDEpvjrX3Uiy8T2nOWoWC/ZmK55Bbw2x4=,tag:0B94qRRc75Te7CnxPD/yzg==,type:str]
    #ENC[AES256_GCM,data:wOYDovtf/kKF3FTuU+zJKwnHEnqeZDZ2/vuMrjh/14LEEA==,iv:8WBL/kV7pZO96RW17QRcS7PZA8WQ+DwbwiwIkOTke5A=,tag:6icPrqqdQ24C3X1pZQLy0A==,type:comment]
    SECRET_WG_EASY_ADMIN_USER: ENC[AES256_GCM,data:EpfSG2Q=,iv:12onMb+SfiZe7iWlsNedvjmAoDSvfdsYAVng0eOi404=,tag:A+6dNTWZVCGsEXNzkzVicg==,type:str]
    SECRET_WG_EASY_ADMIN_PASSWORD: ENC[AES256_GCM,data:UB8ambnffo0=,iv:HeGSnIoGfJ1sazDjAsjCXFkCpi6/DMZhABrvnztb4l8=,tag:rjd03+0EofczjJfJsyt3MQ==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:f8huroLIwJY=,iv:TmGo7W6ZIULnt1OQQvBX0trGeeD0yzx38qJy0GmhGIE=,tag:3Bvy/jVnCDxpIVDIgPMnNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMHZTRVFnVWRJOEQvNTJD
            dFp6THY2TDY5WXJrVzhnZkl5eTYrbk5PZ2tZCnVVS1llaGFaTWZKdjl4aW9WS3ZK
            RzgzLy9qenVqcDBMei9tQTN5bEVWUk0KLS0tIDY0WTNFWTVGUlNIZkthN3hrWWFW
            QWJBaDJadkt6TE9MdWVXelU5VGt6Z0EKqBrXfWl7EIIZQgtnjYMixO9/Lw5WsSgh
            aoZJTE24/dM9vzyMG5pw1A0js3B5jjTpnSdbPpduR2TwdyeOf06G+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T11:24:25Z"
    mac: ENC[AES256_GCM,data:ZumuY13Hva9dfMrc2lSigbiHrvGpjf4nXHfG1GCAGCuwVdl2h7ZgWynVF1YNtKXXJbwYSRTUSYktUrOB+WPKKHn6/CR9S9v1KuV2/zSoGJATejIBlwBXUMJZiH8NFXXncKZiIguh9TxzPLOg4WZcf9xcbwy/0jW2eRtBlZbj9Pc=,iv:/vbQnlGaGC+e7t7DCTOLB3m6wxWnkfMIwYfmzqxG+5k=,tag:LybrY5peu0eMcYaekg/bDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
