---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: wireguard
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  # install:
  #   createNamespace: true
  #   remediation:
  #     retries: 5
  # upgrade:
  #   remediation:
  #     retries: 5
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
    #persistence:
    #  enabled: true
    configSecret:
      enabled: true
      config: ${SECRET_WIREGUARD_CONFIG}
    ingress:
      main:
        enabled: true
