kind: Secret
ansible_user: ENC[AES256_GCM,data:lNrpS0dp,iv:O+0CJi6Y9gwGVwbnjY2IBAR6Xpeedop0kzbDt7YT1Lc=,tag:GswTnm5LhD19n4dCXn+eew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jLBC6DsXYw==,iv:91k5771CiF+w4S/XwtrUGy28zwh8HDn7cMoLeQQuN8g=,tag:uPAf4vae9L9QIpB8Vd4cmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUladXhtQUMyenYzZGNq
            YTh5bnY3SnIrSVFxUGtKTTJZMlM5OFFrRFFNCjBPelBhT2tPZUxNU1VocnVWZFdG
            OVlld2hWb3BEbVVXS2l0YlUrdnFNaDQKLS0tIExpUDhwdTNJQ2pRZVd0WHltVDc1
            akxiazJuRXRhMWFZaWJvRkpnbkZZL2cKw6SH79iD+LeUP8e7U57Keny8+yF8FxuW
            ncBCf5MPXhylFBP7wb7/qw7Io+1O46MZfFXJfAag+7+gP54r8hAv0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T10:27:34Z"
    mac: ENC[AES256_GCM,data:/w5VG3vqsq+PHurNDdP4fn2oqqzRm5/pwxaa7ZzH3X5epDi7bF2caIGxrM9Qm1T4DUZLeaaK3pRvJdmZJKDJM6ETmBLk9SefxmC/xZJk+QQVuXQwgaDqMpZMor2A+Qftrc0NkuEmX2MXWxyV97AahA7WMUHmC82a9IvFwUG7uYM=,iv:l+zTJ7y2RRxzveE5QgqdztPAZSGK6I6rCIjHbFxZVKw=,tag:N1H8w/KaFa1VG/mAfdaSJA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
