kind: Secret
ansible_user: ENC[AES256_GCM,data:8l+8liUz,iv:t6Mm4ERcxQ+4pPnS8D/OVkevgGeBiC5irIIIGN24kLE=,tag:oKDve+7Ot3uJjN09gG+h1A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wzIt9vdiTg==,iv:wqOXkIjnIllcbkOlbdG9Tk6wkCrjFLg/KsKZAk81BKs=,tag:U9piqELLH5DTvm9x+w5U1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL1l1NlJ2cTIxUWRpcFg3
            bWhYTk1UZFJqVmloVTY1dXpSTzI4bEhPVEJFCjA3TzlicXB2SDV6T21TN3A2NmJw
            bzQxY3NDbDZFaDNjZFU5WlM5VllnTzgKLS0tIFVjODc2QTBmQlFmaGZ2RzNGZmlE
            R2dFSVY1OG5sc2NPYkZLcWJVYWFuVzQKzVlgU2fP6+OLK6CuEqlNGwC9dqT0NdQ7
            h0b2L6dMXpq9J4eLE7jldwIVpNAnBciJ/eI7YsE1AYkoNkKOIuYAjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T14:09:44Z"
    mac: ENC[AES256_GCM,data:9qKvN0GiRTxdAobUF3FKL9ANjsAtPwR1lzmZaeyQlHeSAgaFwaqZYsnDUti/Q71y/WJRxGK22SewrqRX2mZAFRmTv4A2e5PCWz/WDas95kKXgqRXnp4oARp3j7qnqfFqHWnxlSrOz8wIvdn53d/oPo6aRyVPuFDRpiuXHKbvpcU=,iv:UJA0Nymu7IEw06uauvxZm38q6RJ72W3xLcqIkOMf5eg=,tag:gzbADymBRWkLSKgb6CPmJA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
