---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
      UID: 1000
      GUID: 1000
      #PHOTOPRISM_WORKERS: 2
      PHOTOPRISM_DATABASE_DRIVER: mysql
      #oauth middleware
      PHOTOPRISM_PUBLIC: true
      #PHOTOPRISM_THUMB_UNCACHED: true
      #PHOTOPRISM_THUMB_SIZE: 720
      #PHOTOPRISM_THUMB_SIZE_UNCACHED: 720
      #PHOTOPRISM_JPEG_SIZE: 720
      #PHOTOPRISM_JPEG_QUALITY: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-video"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.${SECRET_DOMAIN}/oauth2/start?rd=https://$host"
          nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth"
        hosts:
          - host: "photoprism.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "photoprism.${SECRET_DOMAIN}"
            secretName: "photoprism-tls"
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
      originals:
        enabled: true
        existingClaim: "nfs-archivio-personale"

    # mariadb
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
    podAnnotations:
      backup.velero.io/backup-volumes: config,data
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 3000m
