---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 7.3.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      hajimari.io/enable: "true"
      hajimari.io/icon: "weather-sunset"
    hosts:
      - host: "oauth2.${SECRET_DOMAIN}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "oauth2.${SECRET_DOMAIN}"
        secretName: "oauth2-tls"
