---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wg-access-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-access-server
      version: v0.4.6
      sourceRef:
        kind: HelmRepository
        name: wg-access-server
        namespace: flux-system
      interval: 15m
  # install:
  #   createNamespace: true
  #   remediation:
  #     retries: 5
  # upgrade:
  #   remediation:
  #     retries: 5
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
    web:
      config:
        adminUsername: ${SECRET_WG_ACCESS_SERVER_ADMIN_USER}
        adminPassword: ${SECRET_WG_ACCESS_SERVER_ADMIN_PASSWORD}
    wireguard:
      config:
        privateKey: ${SECRET_WG_ACCESS_SERVER_PRIV_KEY}
    persistence:
      enabled: "true"
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      hosts:
        - host: adguard.${SECRET_DOMAIN}
      tls:
        - hosts:
            - host: adguard.${SECRET_DOMAIN}
          secretName: "tls-wg-access-server"
