---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wg-access-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-access-server
      version: 0.4.7
      sourceRef:
        kind: HelmRepository
        name: wg-access-server
        namespace: flux-system
      interval: 15m
  # install:
  #   createNamespace: true
  #   remediation:
  #     retries: 5
  # upgrade:
  #   remediation:
  #     retries: 5
  values:
    env:
      TZ: ${CONFIG_TIMEZONE}
    web:
      config:
        adminUsername: ${SECRET_WG_ACCESS_SERVER_ADMIN_USER}
        adminPassword: ${SECRET_WG_ACCESS_SERVER_ADMIN_PASSWORD}
    wireguard:
      config:
        privateKey: ${SECRET_WG_ACCESS_SERVER_PRIV_KEY}
    persistence:
      enabled: "true"
