---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wg-access-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: wg-access-server
      version: v0.4.6
      sourceRef:
        kind: HelmRepository
        name: wg-access-server
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
      hosts:
        - "wg.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "wg.${SECRET_DOMAIN}"
          secretName: "wg-access-server-tls"

    web:
      config:
        adminUsername: ""
        adminPassword: ""
