---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/charts
      chart: openebs
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
      interval: 5m
  values:
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    cstor:
      enabled: false
      # for k0s
      csiNode:
        kubeletDir: "/var/lib/k0s/kubelet"
