# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uDV+OPtkdJCUPmFBSW5JdZFNYz/H3HMN+mRJ4ThS+flNQICqMiIU4g==,iv:i6agZTKbHxJq8yNnnTMBFUcznfh9fvJecJwNnemJ4q0=,tag:pGzaND8f+IzWutxhhtbdsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ugl6vh0z58frzaywfxxy9p2586q98gkdk3u4d4dyf0j4yawzn90q4aps7p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYakNzT3ZNTlZiYXFFR2NX
            TWF2SmhsMDhmR0kzdlV4amdtNk1JcHh0TXhNCk8zakoveWcxSTQvUzVmdHpqaEJD
            NWkvWUJWSncwbDFYeFl5UFU1UGZEN0kKLS0tIHdOMGtHdk5nRTBVZGxmSFBadlJq
            TDEwS3VZaWtOZGR0RzFVaVNmNzZWelUKHVwRHwxrya72ID6Z5eEYJR6hKVXcVyq7
            BjGZGl5Sy+dtO1Ga/20xaCBx3D+GUf6wE19SkUx2IYjqbDJRztI5Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T22:09:06Z"
    mac: ENC[AES256_GCM,data:upk7Zjysef2qqFtce03ifw/p8i146G5GMhN/cayDa88j51ymaHOVRP3mcLwO8cajGQuwZtssSdN36ddpi5gczR2MagiiawFRBw0+rnRpjfuOj4nJJC9kTsKWQddJ3io1u1HKB6WDHTCma6tA/gFrIzU1L5oJ0Kcbs3Sn077ZOaA=,iv:vf1GdX6BFh5YvuvoC0DtRKmAn7RZgsnJ0sXxgdyZxG4=,tag:uYsV6HcP89DeriFOW9hfBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
