# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/9tmKic64+khxQZGbsyyLKfBnf0Oigef/NImRFcba50zOqTwPZ0UMQ==,iv:G4pPQ3/s5Vzyg9nFw7i1dItzPOvRrgr7FRvTX3LdxoQ=,tag:Rez/dL3moESdpgW3d+3ZpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcmQrZWhrOU5QcUZMSjNr
            WUVsSEd6Z3RIV1hra3lGQWNsNVkyRzdWTXpJClZ5Wi8vU0RlRTdkb3UrQlNNYTMw
            blZiQW1TbVlqOXJjWmxvMFZPZXVtYlUKLS0tIEJUZXpDcTdnQVFQVlJ0MWl1bWhK
            am1kMzdEbDFPVmlXMkR3Smc1N2lmZFEKxI1ucJb/0SBnDgg9Ar9+WMZiCNcwGxIF
            hrPrb5VQ9Mx3rVy44law4CQL9hJ0kvsJApVg+BdO9qmJqrvZJsoejg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T17:41:25Z"
    mac: ENC[AES256_GCM,data:1jj8v9YH/xG+M616By+oRL/nrJHVcU3e/9ZvbZT50yx6UlSw+7vE9q30eXSHT/3Ge2n+D0v0IWyiXd/h0XvMz+rXtwp07fwxRatagFZzKdeM5yics12/C4mpn+YLS0mNDh7mqIVdl/HhIEFkRNyUsiNAeKOdVigZQ/2JJ+N9mMs=,iv:9T/5hpPZ5+pPxHqQoPRQgLr6mbxyb35anyzWZoXpmHo=,tag:sm19X0n9PMwJ/Wp4QzWBkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
