# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kxl9EgbGi1lHALWtuXjv8LlgYS45iIalq36aN1ObXyrGyVMfiVPZPw==,iv:bMyl+MRoTnVTA+2FcIT0LO+91rBK5eVeDZhR44q8XQ4=,tag:U+pdUH75l+N43W5Hxl1caw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOFU2bkIxZXBrRTdMcUoz
            eUQzS3ltRnFCclNIYnVDRlcrVEF6amxRS1VzCmNCYk0rSERWSUViam80MDhYS24x
            aDJzOGdaUXlobDk4REZjVUxOSkpuTWMKLS0tIDVLZ2V3bVpEWlp6d2xreWRTdUNo
            SHRYVmFLN2lpTVFldTBWNHErZTRobmsKMivBjxxr+gto8xp8SntbFcem2lJpQ0C6
            dLEctRLhZ9YWbKdytgY8i03MxGNGk5suReba6yEdfYlvcQFXixPQ1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T11:08:34Z"
    mac: ENC[AES256_GCM,data:qVpH0EmPEd3rMC82lGrmfZNVqID1qphkPTOBeYDjXsSUxlKB4KinyLf8Oi7BNBr3nbyMjCTQ1iBCbQlHnh9b+ZJCXvr5LNs7q2sD2YXFzDRzwdLWQ3Wegs8VQxCdeoi1+8lIKm8E6ZkHRC3kYUTtiMdeoT8SB/W3fS9UVbJJeJ0=,iv:FN9I16LZwgHPLScA9IvRNVSY59zUeDaOZ+/QOpnRYkk=,tag:kBpVrnF0iVBjAfqUcwPqcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
