# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1hsEJpvY4NVRMqSV5LEWGIdgWdvtfPnWXrxHf1IAmlQNv0+M4plHeQ==,iv:c1167zS7gZJCVA380jpTYmw4IrKlGuZKE+3sfHLlF+Q=,tag:QBUKvjV/6RoM+sUr/398Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cGdOeUJkcklRMHlLZEQ3
            aFcrczRxR3l5bXZCZFpkclJvaUs1Q1FYMUJZCjNMSUtmWHZ2TDBlMEFXNENEd3U2
            b1Y4Zis0b09kZTk3MjhsV0plUWFyUU0KLS0tIHFHb1RJTUVKd2p2OUtpOFdlM2R6
            UGM5dkFWcnVacjMwQ3BJaUxiQ3RzT3MK1cppbMDaQFpoaDfPAv8pWAyFebkpXFnu
            8Jn332WT1pEOv9vZL1HpGclYrbC2DgowHJaV0iDUbMWDE9IFNDHpzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T19:43:33Z"
    mac: ENC[AES256_GCM,data:UPraJCR6thexkxojfmgWCr5Sum4xIWpIQgLzKtvlJDrVNBONs8CzUxGl60eqdALz45Khla+LK3vcVd9Gk95DH4Rl9IQPMIMOQEbJThlGimlOkaZGZd0d4D2kqzibu7Gvs6Y/qkQedSAcnIXqlUp2evuIcnq9kX2bVxyjbTfB8S4=,iv:Yq30W3t9coiwk1KHaMEoCEMCqBGP7oZ6Mxwl9ty1w3M=,tag:H0emJAY0B2M5sswcmHGrcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
