# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RNovO0HJEMsBTvazmqnI42mxsAa3KDHcHt7A4epzmd7zxPqj+goTBA==,iv:T07T1F18Tw799xvDWi581N6ZUwAabjkqOLS0Uauwg44=,tag:wy1Be6RFSkJLuQmcZ/cBgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7p45g3nejte463zyn35vuz2252p6z4ysjw90n9v5uj85526zq7se8hgtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TVZ4S3k0VEdkK3V0Q3RG
            WkQyUDNwbHFIUS9JQkdZZVNhZlhvdkJWYmdZClE0QWRmQkJpTDJCWTBhM1dLdUw3
            NmQ3RkNwL043L3JDa1B3a1pDSTVHUm8KLS0tIFdjRGJwbk1Vd29icWtwVE5lblRu
            cUpBRkpzRE9Ud3BWOW1BRVE4SGFPUFUKj0AECuPUfzAKELNt46mc1fcKunJKt6jd
            mPfGYiS6u6AJMGfgzXJwR+5T0BaOo3QNS7EW32FJSBlSjh6WGKF83Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T10:31:53Z"
    mac: ENC[AES256_GCM,data:Y6RKS8fhEFpkhKp7w0WooT2IGnWpJyaLIxgI8KhFG8v/CdK4mXuzNdMVdDGn4E/YTBaMSAXVUQDQelEitxFOM3Zf/LpzMKQIBbZoNMEpiz37XHiBq076c48vHrBfCaRbdOYif3OUO2CAJozMf9Ecs7DSuXCkQze7TYBluREbKAg=,iv:F1uc8grwKCTsD6AJmdwWxUrOI8k6HNCBuaf99VqMg50=,tag:ygYyQqIx7xTHGJ3rXK5n7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
