---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 4.0.12
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    mode: standalone
    rootUser: "admin"
    rootPassword: ${SECRET_MINIO_ADMIN_KEY}
    # ingress
    service:
      type: LoadBalancer
      loadBalancerIP: ${CONFIG_LB_IP_MINIO}
    consoleIngress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
        #traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        #traefik.ingress.kubernetes.io/router.middlewares: networking-oauth@kubernetescrd
      hosts:
        - host: "minio-console.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "minio-console.${SECRET_DOMAIN}"
          secretName: "minio-console-tls"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "weather-sunset"
        #traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        #traefik.ingress.kubernetes.io/router.middlewares: networking-oauth@kubernetescrd
      hosts:
        - "minio.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "minio.${SECRET_DOMAIN}"
          secretName: "minio-main-tls"
    persistence:
      enabled: true
      existingClaim: "nfs-minio"
      # size:
    # resources
    resources:
      requests:
        memory:
