---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 128Mi
